### ISSUE TITLE
Auto update on container start?

### ISSUE THREAD

**Issue by 0xdevalias** [linuxserver/docker-plexrequests#1]
I guess this probably wouldn't be needed if the docker container gets linked to updates of the main repo, but another solution could be to have it pull down the latest version when the container starts. Not sure if this would then be better done using git or not.

**Comment by JigSawFr** [comment]
Problem is this container get latest zip release, but package is not updated anymore by repo collaborators...

**Comment by zaggash** [comment]
Hello, do you have any ideas or something similar ?

**Comment by sparklyballs** [comment]
there was a new release recently.
https://github.com/lokenx/plexrequests-meteor/releases/tag/v1.6.2

**Comment by sparklyballs** [comment]
having said that though, it gets the latest tarball of the master at build time.
curl -o /tmp/source.tar.gz -L https://github.com/lokenx/plexrequests-meteor/tarball/master
so that's the latest it can be whenever the image is built

**Comment by zaggash** [comment]
Yep I remember.
If we setup an auto update on restart, it could take about 3-4 minutes to build, depends on the hardware.

I do not know what is the best.
Is it better to trigger an auto build on plexrequest repo commits ?
Or do we accept the restart to be delayed ?

**Comment by 0xdevalias** [comment]
Personally I'd probably prefer auto build on commits, as that should be 'quick enough' for most reasonable instances and also feels less hacky.

Sent from Outlook Mobile

On Fri, Feb 26, 2016 at 12:54 PM -0800, "zaggash" notifications@github.com wrote:

Yep I remember.

If we setup an auto update on restart, it could take about 3-4 minutes to build, depends on the hardware.

I do not know what is the best.

Is it better to trigger an auto build on plexrequest repo commits ?

Or do we accept the restart to be delayed ?

**Comment by openam** [comment]
Is there any way to see if there is something available without having to curl a tar.gz file everytime? Couldn't it just use git, and do `git pull` on the starts after the initial tarball?

FYI there have been a couple more [releases](https://github.com/lokenx/plexrequests-meteor/releases) since 1.6.2.

**Comment by stramel** [comment]
Is anyone getting this to update? I tried rebuilding the docker image and it still seems to be pulling 1.7.2

**Comment by lonix** [comment]
I Don't think compareing the output of https://github.com/lokenx/plexrequests-meteor/releases/latest latest tag should be to hard. (i think it stores current version in version.txt) too.

**Comment by zaggash** [comment]
Let try with this :

curl -sX GET  "https://api.github.com/repos/lokenx/plexrequests-meteor/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]'

**Comment by zaggash** [comment]
The thing is we will need to build on start.
As we said, this will slow down the start.

**Comment by zaggash** [comment]
Working on a branch to allow it.

**Comment by zaggash** [comment]
See PR #5
