### ISSUE TITLE
[Feature Request] Add ability to pull from PlexRequests-meteor's dev-testing branch 

### ISSUE THREAD

**Issue by RickyGrassmuck** [linuxserver/docker-plexrequests#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

One of the Plexrequests-meteor devs here and wanted to see if it would be possible to add the ability to specify a specific branch of the Plexrequests-meteor to use in the container? 

I just added in [Radarr support](https://github.com/lokenx/plexrequests-meteor/pull/434) and created a new branch called dev-testing which will be used for testing new features prior to being merged into Master and it would really help get more users to test out these changes if they were able to simply specify the dev-testing branch in their docker run command and docker-ompose files.

I'm going to look into what that would entail but I'm fairly new to creating containers so if it may be a whole before I'm able to get it working.

Let me know if I can help and if this would be possible.

PS. - Great work guys, have my entire setup based on takes containers and the couldn't be running better!

**Comment by RickyGrassmuck** [comment]
@sparkyballs any update on this? Noticed there are a couple issues open now for this.

If you want we can discuss this in IRC or telegram.

**Comment by sparklyballs** [comment]
our irc channel is #linuxserver.io on freenode

you can find me there and PM if you wish

i'm a bit confused though as i thought plexrequests had become ombi

**Comment by RickyGrassmuck** [comment]
Ombi was previously PlexRequests.net which was a spin-off of our version Plexrequests-meteor. 

Plexrequests-meteor is still actively developed(I'm one of the collaborators).
