### ISSUE TITLE
Radarr integration for Plex Requests

### ISSUE THREAD

**Issue by Kuroyukihimeeee** [linuxserver/docker-plexrequests#12]
Plex Requests supports Sickrage and Sonarr for TV along with Couchpotato. Radarr has recently come along and works (at least for me 10000x better)

Can see it is already over on the lokenx/plexrequests-meteor repo in dev-testing. Would it be possible to add Radarr support alongside Sickrage, Sonarr, etc in a future release on this linuxserver version?

**Comment by foux** [comment]
In other words, it would be nice to be able to switch to the develop github tag, as you're doing for Sonarr

**Comment by sparklyballs** [comment]
not entirely sure where to go with this, i thought plexrequests had been rebranded as ombi ?

**Comment by foux** [comment]
Well Ombi does the same thing as PlexRequests, but it's not the same apps, and PlexRequests is still in active development.

And the Omni docker isn't recommended by the team right now ;) (meaning you @sparklyballs I think ;) )

**Comment by sparklyballs** [comment]
latest release now  has radarr integration.
