### ISSUE TITLE
Meteor recommended Version

### ISSUE THREAD

**Issue by zaggash** [linuxserver/docker-plexrequests#13]
Regarding the documentation, it is recommended to use version 1.3.

⚠️ Warning regarding Meteor 1.3 ⚠️

Meteor recently updated to 1.3, and while we don't expect any issues we advise you don't update your installation yet. You will get prompted to run meteor update once the update has downloaded in the background. Please refrain from running it, until we can confirm everything will continue to work.

**Comment by RickyGrassmuck** [comment]
This can be ignored and I will be removing it from plexrequests README. There have been very few issues resulting from the use of the latest meteor versions and the LinuxServer.io container has been running it fine for sometime now.
