### ISSUE TITLE
Consider migrating this container to Ombi

### ISSUE THREAD

**Issue by patsissons** [linuxserver/docker-plexrequests#14]
[Ombi](http://ombi.io/) is a [port of plexrequests](https://github.com/tidusjar/Ombi) that is much more feature rich. There is already a [docker image for ombi](https://github.com/rogueosb/docker-ombi), but I'm sure other lsio users would love a proper lsio container.

It may also be desired to simply create a new container instead of re-purposing this one.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by sparklyballs** [comment]
what, like this one ? 

https://github.com/linuxserver/docker-ombi

**Comment by patsissons** [comment]
omg, how did I not see this... apparently I am blind this morning.

haha sorry for wasting your time.
