### ISSUE TITLE
Completely remove all traces of Plex Request

### ISSUE THREAD

**Issue by desimaniac** [linuxserver/docker-plexrequests#17]
After removing the container, volumes, images, mounted paths, and recreate the docker image from scratch, it somehow still remembers my previous configuration inside Plex Request. I suppose it's storing the database somewhere else. 

How do I go about completely starting from scratch with no trace of the previous Plex Request info?

Thanks.

**Comment by j0nnymoe** [comment]
Removing the data located in the /config folder you mounted should be more than enough.

**Comment by desimaniac** [comment]
After some digging around, I found out that it is actually storing the information in the host MongoDB. 

You can see for yourself by doing this on your host (unix):

```
mongo
show dbs
use admin #get inside admin database
show collections #we are getting a look at users collection
db.users.find().pretty() #shows user collection where the admin account info is located
exit
```

Since there is no way to reset the password within the GUI, you have to delete the user account and create a new one. To do that just add this line:
```
db.users.drop() #remove users collection; output true if successful
```

**Comment by j0nnymoe** [comment]
I'm going to guess this is a niche issue as you have mongo already running on your host. This is the first report we've had on this happening. I'm going to close this issue now it is fixed but if it happens again, please post some more information about your setup/docker run command.

**Comment by desimaniac** [comment]
Ok. Thanks.

**Comment by aptalca** [comment]
Most likely you were running the container in host mode (as opposed to bridge), which exposed the host's mongodb to the container through 127.0.0.1:27017, which is how plexrequests connects to mongodb inside the container

**Comment by desimaniac** [comment]
Oh okk... yeah I did run it as host mode (`--net="host"`).. Go figure!  

I guess I should redo it in bridge mode then. Do you have any suggestions on how to remove all the plexrequest traces from the host MongoDB?

**Comment by aptalca** [comment]
No, I am afraid not. You might want to ping the plexrequest devs on their plex forum thread or github.

**Comment by desimaniac** [comment]
Gotcha. Thanks for the info though. At least things make sense now.. :p
