### ISSUE TITLE
Plexrequests github repo release content is not matching content inside container

### ISSUE THREAD

**Issue by alexwitherspoon** [linuxserver/docker-plexrequests#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Plexrequests container is not functional because it's not updated to accept a bug: https://github.com/lokenx/plexrequests-meteor/issues/492 This change doesn't appear to be reflected in the container: https://github.com/lokenx/plexrequests-meteor/commit/51d1ca2cfa4a35fd289dd1963252d7c86d309e5b#diff-5e737f386fad28d4cb1c1f0e42f1fdd9

I'll see if I can suggest a fix, reading~

**Comment by sparklyballs** [comment]
the update from source that addressed this issue came after our last weekly update

manually triggered update to pick this up and the image refresh should be available reasonably soon
