### ISSUE TITLE
Requesting a manual image rebuild against release v1.21.1

### ISSUE THREAD

**Issue by RickyGrassmuck** [linuxserver/docker-plexrequests#20]
I just pushed out a new release that fixes an issue with poster urls that became broken when TMDB changed the available sizes(and thus the link paths).

I know a large amount of our users are running y'alls container and also that image builds are typically only done automatically on Fridays. If you could do an emergency rebuild against the new release I and many others would be eternally grateful(need posters!).

Thanks for all the hard work!

**Comment by sparklyballs** [comment]
just triggered a build 

if it helps i could give you a webhook address that would trigger our jenkins

but not in an open method like here

perhaps you could join our discord channel and i could dm you https://discord.gg/YWrKVTn
