### ISSUE TITLE
Use tagged build rather then master ?

### ISSUE THREAD

**Issue by lonix** [linuxserver/docker-plexrequests#3]
Consider using the latest tag: https://github.com/lokenx/plexrequests-meteor/releases/latest rather than using the latest master commit. this is not a repo that versions in master but rather as a tag.

**Comment by sparklyballs** [comment]
at the time this container was made the releases were not maintained and were behind master by months.

**Comment by sparklyballs** [comment]
https://github.com/linuxserver/docker-plexrequests/issues/1#issuecomment-187856765
